# Generated by Django 4.2.6 on 2023-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitems',
            name='product_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
